# Generated by Django 4.2.1 on 2023-05-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='project',
            name='people_involved',
        ),
        migrations.AddField(
            model_name='project',
            name='people_involved',
            field=models.ManyToManyField(related_name='projects_involved_in', to='project_portal.person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposer_projects', to='project_portal.person'),
        ),
    ]
